# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 10:30
from __future__ import unicode_literals

import pytz
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logline',
            name='updated_at',
            field=models.DateTimeField(
                default=datetime.datetime.now(tz=pytz.UTC)),
            preserve_default=False,
        ),
    ]
