# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import psc.product.utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to=psc.product.utils.get_images_upload_path),
        ),
    ]
