# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170622_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='crop_type',
            field=models.CharField(choices=[('th', 'Thumbnail')], default='th', max_length=2),
            preserve_default=False,
        ),
    ]
