# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 09:11
from __future__ import unicode_literals

import pytz
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170705_0911'),
        ('product', '0004_auto_20170623_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime.now(tz=pytz.UTC)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
