# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20170705_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_ready',
            field=models.BooleanField(default=False),
        ),
    ]
