# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_image_image_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='product_position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
