# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_image_product_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.SlugField(max_length=255)),
                ('description', models.TextField()),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='documentation',
            name='type',
            field=models.CharField(choices=[('doc', 'doc'), ('docx', 'docx'), ('pdf', 'pdf'), ('csv', 'csv'), ('xls', 'xls'), ('xlsx', 'xlsx'), ('odf', 'odf'), ('odt', 'odt')], max_length=4),
        ),
    ]
