# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20170724_0927'),
        ('product', '0013_auto_20170718_1118'),
    ]

    operations = [
    ]
