# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_company_company_logo'),
        ('product', '0014_merge_20170724_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
