# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20170724_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_edited_outside',
            field=models.BooleanField(default=False),
        ),
    ]
