# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 12:51
from __future__ import unicode_literals
from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_superuser(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return

    User = apps.get_registered_model('users', 'User')
    admin = User(
        username='admin',
        email='admin@example.com',
        password=make_password('Anvil8team!'),
        is_superuser=True,
        is_staff=True,
    )
    admin.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170704_0839'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
