# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 09:11
from __future__ import unicode_literals

import pytz
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime.now(tz=pytz.UTC)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime.now(tz=pytz.UTC)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
