# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 10:23
from __future__ import unicode_literals

import pytz
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170705_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='edited_at',
        ),
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime.now(tz=pytz.UTC)),
            preserve_default=False,
        ),
    ]
