# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_account_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='activated',
        ),
        migrations.RemoveField(
            model_name='account',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='account',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='user',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
