# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 10:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_activateemailkeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='activateemailkeys',
            name='created_at',
            field=models.DateField(auto_created=True, default=datetime.date(2017, 7, 7)),
            preserve_default=False,
        ),
    ]
