# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20170707_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activateemailkeys',
            name='created_at',
            field=models.DateField(),
        ),
    ]
