# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_invitationkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_level',
            field=models.SmallIntegerField(choices=[(1, 'Owner'), (2, 'Editor')], default=2),
        ),
    ]
