# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationkey',
            name='access_level',
            field=models.SmallIntegerField(choices=[(1, 'Owner'), (2, 'Editor')], default=2),
        ),
    ]
