# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_invitationkey_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationkey',
            name='access_level',
            field=models.SmallIntegerField(choices=[(None, 'Choice Access Level'), (1, 'Owner'), (2, 'Editor')], default=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.SmallIntegerField(choices=[(None, 'Choice Access Level'), (1, 'Owner'), (2, 'Editor')], default=2),
        ),
    ]
