# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-27 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'Account Approved'), (2, 'Company Approved'), (3, 'Company Deny'), (4, 'Product Approved'), (5, 'Product Deny'), (6, 'Account Multiple users activated'), (7, 'Account Multiple company activated')])),
                ('status', models.SmallIntegerField(choices=[(1, 'New'), (2, 'Read'), (3, 'Archived')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
