# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-27 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'New'), (2, 'Read'), (3, 'Archived')], default=1),
        ),
    ]
