# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-27 09:55
from __future__ import unicode_literals

import pytz
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20170727_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime.now(tz=pytz.UTC)),
            preserve_default=False,
        ),
    ]
