# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-27 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='instance_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
