# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_instance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Account Approved'), (2, 'Company Approved'), (3, 'Company Deny'), (4, 'Product Approved'), (5, 'Product Deny'), (6, 'Account Multiple users activated'), (7, 'Account Multiple company activated'), (8, 'Invited user registered')]),
        ),
    ]
