# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170725_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='contact_information',
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
    ]
