# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
