# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 12:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170725_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_contact_information',
            field=models.ManyToManyField(blank=True, related_name='user_contact_information', to=settings.AUTH_USER_MODEL),
        ),
    ]
