# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(default='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='short_description',
            field=models.CharField(default='Short Description', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(default='http://example.com'),
            preserve_default=False,
        ),
    ]
