# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20170724_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_logo',
        ),
    ]
