# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_company_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=16)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='companies.Company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='headquarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headquarter', to='companies.Office'),
        ),
    ]
