# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 10:06
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20170724_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
