# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import psc.product.utils


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('png', 'png'), ('jpeg', 'jpeg'), ('gif', 'gif')], max_length=4)),
                ('crop_type', models.CharField(choices=[('th', 'Thumbnail'), ('pl', 'Product Listing'), ('pr', 'Product Detail'), ('co', 'Company Logo')], max_length=2)),
                ('path', models.ImageField(blank=True, null=True, upload_to=psc.product.utils.get_images_upload_path)),
                ('image_ready', models.BooleanField(default=False)),
                ('product_position', models.IntegerField()),
                ('is_edited_outside', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
